# Generated by Django 5.0.3 on 2024-09-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudantes',
            new_name='Estudante',
        ),
    ]
